Document: inwt
Title: Debian inwt Manual
Author: <insert document author here>
Abstract: This manual describes what inwt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/inwt/inwt.sgml.gz

Format: postscript
Files: /usr/share/doc/inwt/inwt.ps.gz

Format: text
Files: /usr/share/doc/inwt/inwt.text.gz

Format: HTML
Index: /usr/share/doc/inwt/html/index.html
Files: /usr/share/doc/inwt/html/*.html
