Document: r-3.6.0
Title: Debian r-3.6.0 Manual
Author: <insert document author here>
Abstract: This manual describes what r-3.6.0 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/r-3.6.0/r-3.6.0.sgml.gz

Format: postscript
Files: /usr/share/doc/r-3.6.0/r-3.6.0.ps.gz

Format: text
Files: /usr/share/doc/r-3.6.0/r-3.6.0.text.gz

Format: HTML
Index: /usr/share/doc/r-3.6.0/html/index.html
Files: /usr/share/doc/r-3.6.0/html/*.html
