Document: r-3.6.0-packages
Title: Debian r-3.6.0-packages Manual
Author: <insert document author here>
Abstract: This manual describes what r-3.6.0-packages is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/r-3.6.0-packages/r-3.6.0-packages.sgml.gz

Format: postscript
Files: /usr/share/doc/r-3.6.0-packages/r-3.6.0-packages.ps.gz

Format: text
Files: /usr/share/doc/r-3.6.0-packages/r-3.6.0-packages.text.gz

Format: HTML
Index: /usr/share/doc/r-3.6.0-packages/html/index.html
Files: /usr/share/doc/r-3.6.0-packages/html/*.html
